version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_aws}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
      - "9000:9000"
      #- "127.0.0.1:53:53"                # DNS config (only required for Pro)
      #- "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      #- "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      #- SERVICES=es,dynamodb,sqs,sns
      - DEBUG=${DEBUG-1}
      - PERSISTENCE=${PERSISTENCE-1}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/data
      - START_WEB=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
